### ISSUE TITLE
dompmsuspend test failures

### ISSUE THREAD

**Issue by jferlan** [autotest/tp-libvirt#14]
Prior to the split of virt-test/tp-libvirt, the following pull request:

https://github.com/autotest/virt-test/pull/1242

added the test for 'dompmsuspend'.  Running that under f19 (or f20) using either the provided libvirt or a git top of trunk installed libvirt results in two failures in my testing which need to be resolved. Whether it's a libvirt or test bug I'm not quite sure yet, but I wanted to be sure to log it as an issue to ensure followup!

Errors are as follows from debug.log output:

Failure 1:

```
04:24:37 DEBUG| Sending command: rpm -q qemu-guest-agent || yum install -y qemu-guest-agent
04:24:38 DEBUG| Sending command: echo $?
04:24:38 DEBUG| Sending command: ps aux |grep [q]emu-ga
04:24:38 DEBUG| Sending command: echo $?
04:24:38 DEBUG| Sending command: rpm -q pm-utils || yum install -y pm-utils
04:24:38 DEBUG| Sending command: echo $?
04:24:38 DEBUG| Running virsh command: dompmsuspend virt-tests-vm1 disk --duration 0
04:24:38 DEBUG| Running '/usr/bin/virsh dompmsuspend virt-tests-vm1 disk --duration 0'
04:24:39 DEBUG| status: 1
04:24:39 DEBUG| stdout:
04:24:39 DEBUG| stderr: error: Domain virt-tests-vm1 could not be suspended
error: internal error: unable to execute QEMU agent command 'guest-suspend-disk': child process has failed to suspend
04:24:41 DEBUG| Undefine VM virt-tests-vm1
04:24:41 DEBUG| Define VM from /tmp/xml_utils_temp_S3dKiq.xml
04:24:41 DEBUG| Checking image file /home/virt-test/shared/data/images/jeos-19-64.qcow2
04:24:41 DEBUG| Running '/bin/qemu-img info /home/virt-test/shared/data/images/jeos-19-64.qcow2'
04:24:41 DEBUG| Running '/bin/qemu-img check /home/virt-test/shared/data/images/jeos-19-64.qcow2'
04:24:42 ERROR|
04:24:42 ERROR| Traceback (most recent call last):
04:24:42 ERROR|   File "/home/virt-test/virttest/standalone_test.py", line 213, in run_once
04:24:42 ERROR|     run_func(self, params, env)
04:24:42 ERROR|   File "/home/virt-test/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py", line 81, in run_virsh_dompmsuspend
04:24:42 ERROR|     raise error.TestFail("Run failed with right command")
04:24:42 ERROR| TestFail: Run failed with right command
04:24:42 ERROR|
04:24:42 ERROR| FAIL type_specific.io-github-autotest-libvirt.virsh.dompmsuspend.running.disk -> TestFail: Run failed with right command
```

Failure 2

```
04:25:10 DEBUG| Sending command: rpm -q qemu-guest-agent || yum install -y qemu-guest-agent
04:25:10 DEBUG| Sending command: echo $?
04:25:10 DEBUG| Sending command: ps aux |grep [q]emu-ga
04:25:10 DEBUG| Sending command: echo $?
04:25:10 DEBUG| Sending command: rpm -q pm-utils || yum install -y pm-utils
04:25:10 DEBUG| Sending command: echo $?
04:25:11 DEBUG| Running virsh command: dompmsuspend virt-tests-vm1 hybrid --duration 0
04:25:11 DEBUG| Running '/usr/bin/virsh dompmsuspend virt-tests-vm1 hybrid --duration 0'
04:25:12 DEBUG| status: 1
04:25:12 DEBUG| stdout:
04:25:12 DEBUG| stderr: error: Domain virt-tests-vm1 could not be suspended
error: internal error: unable to execute QEMU agent command 'guest-suspend-hybrid': child process has failed to suspend
04:25:13 DEBUG| Undefine VM virt-tests-vm1
04:25:13 DEBUG| Define VM from /tmp/xml_utils_temp_LzteEJ.xml
04:25:13 DEBUG| Checking image file /home/virt-test/shared/data/images/jeos-19-64.qcow2
04:25:13 DEBUG| Running '/bin/qemu-img info /home/virt-test/shared/data/images/jeos-19-64.qcow2'
04:25:13 DEBUG| Running '/bin/qemu-img check /home/virt-test/shared/data/images/jeos-19-64.qcow2'
04:25:13 ERROR|
04:25:13 ERROR| Traceback (most recent call last):
04:25:13 ERROR|   File "/home/virt-test/virttest/standalone_test.py", line 213, in run_once
04:25:13 ERROR|     run_func(self, params, env)
04:25:13 ERROR|   File "/home/virt-test/test-providers.d/downloads/io-github-autotest-libvirt/libvirt/tests/src/virsh_cmd/domain/virsh_dompmsuspend.py", line 81, in run_virsh_dompmsuspend
04:25:13 ERROR|     raise error.TestFail("Run failed with right command")
04:25:13 ERROR| TestFail: Run failed with right command
04:25:13 ERROR|
04:25:13 ERROR| FAIL type_specific.io-github-autotest-libvirt.virsh.dompmsuspend.running.hybrid -> TestFail: Run failed with right command
```

**Comment by sathnaga** [comment]
Closing as per previous commit merge.
